# Generated by Django 3.0.4 on 2020-05-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileStorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filestorage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='filestorage',
            name='title',
        ),
        migrations.AddField(
            model_name='filestorage',
            name='data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='invoice_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filestorage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fileStorage', to=settings.AUTH_USER_MODEL),
        ),
    ]
