# Generated by Django 3.0.4 on 2020-03-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='comapny name')),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
                ('gstin_no', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('account_no', models.CharField(max_length=12)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('state_code', models.CharField(max_length=6)),
                ('country_code', models.IntegerField()),
                ('signature', models.ImageField(upload_to='company/sign/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
