# Generated by Django 3.0.4 on 2020-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_no',
            field=models.IntegerField(default=0),
        ),
    ]
