# Generated by Django 3.0.4 on 2020-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200503_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cgst_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='igst_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sgst_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
