# Generated by Django 3.0.4 on 2020-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200503_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST'),
        ),
        migrations.AlterField(
            model_name='company',
            name='account_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Account No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cgst_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CGST'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.IntegerField(verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='igst_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='IGST'),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_no',
            field=models.IntegerField(default=0, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pan No'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pincode',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sgst_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='SGST'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Tel'),
        ),
    ]
